# Generated by Django 3.2.1 on 2021-06-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teamstatus_team_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamstatus',
            old_name='team_id',
            new_name='team',
        ),
    ]
