# Generated by Django 3.2.1 on 2021-06-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='team_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='app.team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='team_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='app.team'),
        ),
    ]
