# Generated by Django 3.2.1 on 2021-06-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_game_prev_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='prev_game',
        ),
        migrations.CreateModel(
            name='GameRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='app.game')),
                ('prev_game_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_game_one', to='app.game')),
                ('prev_game_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_game_two', to='app.game')),
            ],
            options={
                'db_table': 'game_rel',
            },
        ),
    ]
