# Generated by Django 3.2.1 on 2021-06-24 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210623_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prediction',
            name='team',
        ),
        migrations.AddField(
            model_name='prediction',
            name='losing_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='losing_team', to='app.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prediction',
            name='winning_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='winning_team', to='app.team'),
            preserve_default=False,
        ),
    ]
