# Generated by Django 3.2.1 on 2021-06-24 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_prediction_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerel',
            name='next_game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_game', to='app.game'),
        ),
        migrations.AlterField(
            model_name='gamerel',
            name='prev_game_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_game_one', to='app.game'),
        ),
        migrations.AlterField(
            model_name='gamerel',
            name='prev_game_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev_game_two', to='app.game'),
        ),
    ]
